# Goal: To run the Continous Integration (CI) for this project

name: CI

on: 
    push:

jobs:
    # Code
    code:
        uses: ./.github/workflows/lint_and_test.yml
    
    # Build
    build-and-push:
        secrets: inherit
        needs: code
        uses: ./.github/workflows/docker.yml
    
    # Deploy
    deploy:
        secrets: inherit
        needs: [code,build-and-push]
        uses: ./.github/workflows/cd.yml