# Goal: To build a CI/CD Pipeline (Just Dummy)

name: CICD Demo

on: 
 push:

jobs:
#CI
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v7
        
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build the code with Docker
        uses: docker/setup-buildx-action@v3
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the application
        run: echo "Test Passed"
        
  deploy:
  #CD
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app on Server
        run: echo "Application Deployed"
