# Goal: To Say Hello and tell the Title / Name of Repository

# Start with naming your Workflow
name: Hello

# When the Workflow runs
on:
 # push:
 # paths-ignore:
 # - 'README.md'
 workflow_dispatch:

jobs:
  # name of your workflow
  greet:
    # Where the Job runs (OS)
    runs-on: ubuntu-latest

    # The sequence of steps the Job does
    steps:
      - name: Say Hello
        run: echo "Hello Friends"

  repo-name:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - name: Show Repository Name
        run: echo "The Repo Name is ${{ github.event.repository.name }}"
