# Goal: To check if the python code is syntactically correct

name: Code Lint

on:
  push:

jobs:
  code-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Code Lint
        run: ruff check .