# Goal : To scan the code for tokens, secrets, API Keys, or any leaked Passwords so that
# if found, we can quickly rotate the exposed tokens/keys/etc

# name of the workflow
name: Secrets Scan

# Reusable Workflow which can be called again and again wherever needed
on: 
    workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0 # from the very first commit pull all the code

            - name: Scan for Leaks
              uses: dortort/betterleaks-action@v0.1.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                config: .github/.gitleaks.toml 
              continue-on-error: true 
            


